query:
    groupby:
    - table
    - varname0
    - selection
    - SingleMuonTriggered
    - METTriggered
    - parent
    - binvar0
    tables:
        central: Events
    aliases: {}
    eval:
    -   METTriggered: 'df: df.HLT_PFMETNoMu90_PFMHTNoMu90_IDTight | df.HLT_PFMETNoMu100_PFMHTNoMu100_IDTight
            | df.HLT_PFMETNoMu110_PFMHTNoMu110_IDTight | df.HLT_PFMETNoMu120_PFMHTNoMu120_IDTight
            | (df.HLT_PFMET170_NotCleaned & (df.run<276282)) | (df.HLT_PFMET170_BeamHaloCleaned
            & (df.run<276282)) | df.HLT_PFMET170_HBHECleaned | df.HLT_PFMET170_HBHE_BeamHaloCleaned
            | df.HLT_MET75_IsoTrk50'
    -   SingleMuonTriggered: 'df: df.HLT_IsoMu24 | df.HLT_IsoTkMu24'
    -   SingleElectronTriggered: 'df: df.HLT_Ele27_WPTight_Gsf'
    -   METnoX_pt_bin: 'df: np.floor(df.METnoX_pt/5.)*5'
    cutflows:
        Monojet:
            selection_name: Monojet
            selection: (IsCertified) & (Flag_goodVertices) & (Flag_globalSuperTightHalo2016Filter)
                & (Flag_HBHENoiseFilter) & (Flag_HBHENoiseIsoFilter) & (Flag_EcalDeadCellTriggerPrimitiveFilter)
                & (Flag_BadPFMuonFilter) & (MET_dCaloMET<0.6) & (nJetSelection>0)
                & (nJetSelection==nJetVeto) & (LeadJetSelection_pt>200.) & (LeadJetSelection_chHEF>0.1)
                & (LeadJetSelection_neHEF<0.8) & (nPhotonVeto==0) & (nBJetVeto==0)
                & (MinDPhiJ1234METnoX>0.5) & (nMuonVeto==0) & (nElectronVeto==0) &
                (nTauVeto==0)
            weight: '1.'
            hists: &id001
            - METnoX_pt
        SingleMuon:
            selection_name: SingleMuon
            selection: (IsCertified) & (Flag_goodVertices) & (Flag_globalSuperTightHalo2016Filter)
                & (Flag_HBHENoiseFilter) & (Flag_HBHENoiseIsoFilter) & (Flag_EcalDeadCellTriggerPrimitiveFilter)
                & (Flag_BadPFMuonFilter) & (MET_dCaloMET<0.6) & (nJetSelection>0)
                & (nJetSelection==nJetVeto) & (LeadJetSelection_pt>200.) & (LeadJetSelection_chHEF>0.1)
                & (LeadJetSelection_neHEF<0.8) & (nPhotonVeto==0) & (nBJetVeto==0)
                & (MinDPhiJ1234METnoX>0.5) & (nMuonVeto==1) & (nElectronVeto==0) &
                (nTauVeto==0) & (nMuonSelection==1) & (MTW<125.) & (MTW>25.)
            weight: '1.'
            hists: *id001
        DoubleMuon:
            selection_name: DoubleMuon
            selection: (IsCertified) & (Flag_goodVertices) & (Flag_globalSuperTightHalo2016Filter)
                & (Flag_HBHENoiseFilter) & (Flag_HBHENoiseIsoFilter) & (Flag_EcalDeadCellTriggerPrimitiveFilter)
                & (Flag_BadPFMuonFilter) & (MET_dCaloMET<0.6) & (nJetSelection>0)
                & (nJetSelection==nJetVeto) & (LeadJetSelection_pt>200.) & (LeadJetSelection_chHEF>0.1)
                & (LeadJetSelection_neHEF<0.8) & (nPhotonVeto==0) & (nBJetVeto==0)
                & (MinDPhiJ1234METnoX>0.5) & (nMuonVeto==2) & (nElectronVeto==0) &
                (nTauVeto==0) & (nMuonSelection==2) & (MLL<111.) & (MLL>71.)
            weight: '1.'
            hists: *id001
        TripleMuon:
            selection_name: TripleMuon
            selection: (IsCertified) & (Flag_goodVertices) & (Flag_globalSuperTightHalo2016Filter)
                & (Flag_HBHENoiseFilter) & (Flag_HBHENoiseIsoFilter) & (Flag_EcalDeadCellTriggerPrimitiveFilter)
                & (Flag_BadPFMuonFilter) & (MET_dCaloMET<0.6) & (nJetSelection>0)
                & (nJetSelection==nJetVeto) & (LeadJetSelection_pt>200.) & (LeadJetSelection_chHEF>0.1)
                & (LeadJetSelection_neHEF<0.8) & (nPhotonVeto==0) & (nBJetVeto==0)
                & (MinDPhiJ1234METnoX>0.5) & (nMuonVeto==3) & (nElectronVeto==0) &
                (nTauVeto==0) & (nMuonSelection==3)
            weight: '1.'
            hists: *id001
        SingleElectron:
            selection_name: SingleMuon
            selection: (IsCertified) & (Flag_goodVertices) & (Flag_globalSuperTightHalo2016Filter)
                & (Flag_HBHENoiseFilter) & (Flag_HBHENoiseIsoFilter) & (Flag_EcalDeadCellTriggerPrimitiveFilter)
                & (Flag_BadPFMuonFilter) & (MET_dCaloMET<0.6) & (nJetSelection>0)
                & (nJetSelection==nJetVeto) & (LeadJetSelection_pt>200.) & (LeadJetSelection_chHEF>0.1)
                & (LeadJetSelection_neHEF<0.8) & (nPhotonVeto==0) & (nBJetVeto==0)
                & (MinDPhiJ1234METnoX>0.5) & (nMuonVeto==0) & (nElectronVeto==1) &
                (nTauVeto==0) & (nElectronSelection==1) & (MTW<125.) & (MTW>25.)
            weight: '1.'
            hists: *id001
        DoubleElectron:
            selection_name: SingleMuon
            selection: (IsCertified) & (Flag_goodVertices) & (Flag_globalSuperTightHalo2016Filter)
                & (Flag_HBHENoiseFilter) & (Flag_HBHENoiseIsoFilter) & (Flag_EcalDeadCellTriggerPrimitiveFilter)
                & (Flag_BadPFMuonFilter) & (MET_dCaloMET<0.6) & (nJetSelection>0)
                & (nJetSelection==nJetVeto) & (LeadJetSelection_pt>200.) & (LeadJetSelection_chHEF>0.1)
                & (LeadJetSelection_neHEF<0.8) & (nPhotonVeto==0) & (nBJetVeto==0)
                & (MinDPhiJ1234METnoX>0.5) & (nMuonVeto==0) & (nElectronVeto==2) &
                (nTauVeto==0) & (nElectronSelection==2) & (MLL<111.) & (MLL>71.)
            weight: '1.'
            hists: *id001
    hists:
        METnoX_pt:
        -   table: 'df: ''{table_name}'''
        -   varname0: 'df: ''METnoX_pt'''
        -   selection: 'df: ''{selection_name}'''
        -   METTriggered: 'df: df.METTriggered'
        -   SingleMuonTriggered: 'df: df.SingleMuonTriggered'
        -   SingleElectronTriggered: 'df: df.SingleElectronTriggered'
        -   parent: 'df: df.parent'
        -   binvar0: 'df: df.METnoX_pt_bin'
        -   count: 'df: 1.'
        -   sum_w: 'df: {weight}'
        -   sum_ww: 'df: df.sum_w**2'
files:
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00000.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00001.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00002.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00003.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00004.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00005.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00006.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00007.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00008.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00009.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00010.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00011.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00012.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00013.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00014.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00015.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00016.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00017.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00018.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00019.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00020.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00021.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00022.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00023.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00024.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00025.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00026.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00027.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00028.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00029.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00030.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00031.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00032.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00033.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00034.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00035.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00036.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00037.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00038.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00039.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00040.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00041.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00042.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00043.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00044.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00045.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00046.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00047.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00048.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00049.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00050.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00051.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00052.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00053.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00054.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00055.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00056.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00057.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00058.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00059.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00060.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00061.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00062.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00063.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00064.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00065.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00066.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00067.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00068.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00069.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00070.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00071.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00072.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00073.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00074.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00075.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00076.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00077.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00078.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00079.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00080.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00081.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00082.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00083.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00084.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00085.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00086.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00087.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00088.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00089.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00090.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00091.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00092.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00093.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00094.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00095.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00096.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00097.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00098.h5
- /vols/build/cms/sdb15/ZinvWidth/zinv-notebooks/notebooks/corrections/triggers/results/skims/Data/result_00099.h5
