selections:
    lumi_selection: "ev, source, nsig: ev.IsCertified(ev)"
    filter_selection:
        "ev, source, nsig: (ev.Flag_goodVertices>0.5)
             & (ev.Flag_globalSuperTightHalo2016Filter>0.5)
             & (ev.Flag_HBHENoiseFilter>0.5)
             & (ev.Flag_HBHENoiseIsoFilter>0.5)
             & (ev.Flag_EcalDeadCellTriggerPrimitiveFilter>0.5)
             & (ev.Flag_BadPFMuonFilter>0.5)
             & (ev.Flag_BadGlobalMuon>0.5)
             & (ev.Flag_CloneGlobalMuon>0.5)
             & ((ev.Flag_eeBadScFilter>0.5) | (np.ones(ev.size, dtype=np.int32)*(~ev.config.dataset.isdata)))"
    met_selection: "ev, source, nsig: ev.METnoX_pt(ev, source, nsig) > 200."
    met_low_selection: "ev, source, nsig: ev.METnoX_pt(ev, source, nsig) <= 200."
    dphi_jet_met_selection: "ev, source, nsig: ev.MinDPhiJ1234METnoX(ev, source, nsig) > 0.5"
    dphi_jet_met_inv_selection: "ev, source, nsig: ev.MinDPhiJ1234METnoX(ev, source, nsig) <= 0.5"
    dcalo_pfmet_selection: "ev, source, nsig: ev.MET_dCaloMET(ev, source, nsig) < 0.6"
    jet_selection:
        "ev, source, nsig: (ev.JetSelection(ev, source, nsig, 'pt').counts > 0)
             & (ev.JetSelection(ev, source, nsig, 'pt').counts == ev.JetVeto(ev, source, nsig, 'pt').counts)"
    lead_jet_selection:
        "ev, source, nsig: (get_nth_object(ev.JetSelection(ev, source, nsig, 'pt'), 0, ev.size)>200.)
             & (get_nth_object(ev.JetSelection(ev, source, nsig, 'chHEF'), 0, ev.size)>0.1)
             & (get_nth_object(ev.JetSelection(ev, source, nsig, 'chHEF'), 0, ev.size)<0.95)"
    muon_0_selection:
        "ev, source, nsig: (ev.MuonSelection(ev, source, nsig, 'pt').counts == ev.MuonVeto(ev, source, nsig, 'pt').counts)
             & (ev.MuonVeto(ev, source, nsig, 'pt').counts == 0)"
    muon_1_selection:
        "ev, source, nsig: (ev.MuonSelection(ev, source, nsig, 'pt').counts == ev.MuonVeto(ev, source, nsig, 'pt').counts)
             & (ev.MuonVeto(ev, source, nsig, 'pt').counts == 1)"
    muon_2_selection:
        "ev, source, nsig: (ev.MuonSelection(ev, source, nsig, 'pt').counts == ev.MuonVeto(ev, source, nsig, 'pt').counts)
             & (ev.MuonVeto(ev, source, nsig, 'pt').counts == 2)"
    muon_3_selection:
        "ev, source, nsig: (ev.MuonSelection(ev, source, nsig, 'pt').counts == ev.MuonVeto(ev, source, nsig, 'pt').counts)
             & (ev.MuonVeto(ev, source, nsig, 'pt').counts == 3)"
    lepton_p1_charge: "ev, source, nsig: ev.LeptonCharge(ev, source, nsig) == 1"
    lepton_zero_charge: "ev, source, nsig: ev.LeptonCharge(ev, source, nsig) == 0"
    lepton_m1_charge: "ev, source, nsig: ev.LeptonCharge(ev, source, nsig) == -1"
    ele_0_selection:
        "ev, source, nsig: (ev.ElectronSelection(ev, source, nsig, 'pt').counts == ev.ElectronVeto(ev, source, nsig, 'pt').counts)
             & (ev.ElectronVeto(ev, source, nsig, 'pt').counts == 0)"
    ele_1_selection:
        "ev, source, nsig: (ev.ElectronSelection(ev, source, nsig, 'pt').counts == ev.ElectronVeto(ev, source, nsig, 'pt').counts)
             & (ev.ElectronVeto(ev, source, nsig, 'pt').counts == 1)"
    ele_2_selection:
        "ev, source, nsig: (ev.ElectronSelection(ev, source, nsig, 'pt').counts == ev.ElectronVeto(ev, source, nsig, 'pt').counts)
             & (ev.ElectronVeto(ev, source, nsig, 'pt').counts == 2)"
    ele_3_selection:
        "ev, source, nsig: (ev.ElectronSelection(ev, source, nsig, 'pt').counts == ev.ElectronVeto(ev, source, nsig, 'pt').counts)
             & (ev.ElectronVeto(ev, source, nsig, 'pt').counts == 3)"
    tau_0_selection:
        "ev, source, nsig: (ev.TauSelection(ev, source, nsig, 'pt').counts == ev.TauVeto(ev, source, nsig, 'pt').counts)
             & (ev.TauVeto(ev, source, nsig, 'pt').counts == 0)"
    tau_1_selection:
        "ev, source, nsig: (ev.TauSelection(ev, source, nsig, 'pt').counts == ev.TauVeto(ev, source, nsig, 'pt').counts)
             & (ev.TauVeto(ev, source, nsig, 'pt').counts == 1)"
    tau_2_selection:
        "ev, source, nsig: (ev.TauSelection(ev, source, nsig, 'pt').counts == ev.TauVeto(ev, source, nsig, 'pt').counts)
             & (ev.TauVeto(ev, source, nsig, 'pt').counts == 2)"
    pho_0_selection:
        "ev, source, nsig: (ev.PhotonSelection(ev, source, nsig, 'pt').counts == ev.PhotonVeto(ev, source, nsig, 'pt').counts)
             & (ev.PhotonVeto(ev, source, nsig, 'pt').counts == 0)"
    bjet_0_selection:
        "ev, source, nsig: (ev.JetBSelection(ev, source, nsig, 'pt').counts == ev.JetBVeto(ev, source, nsig, 'pt').counts)
             & (ev.JetBVeto(ev, source, nsig, 'pt').counts == 0)"
    mtw_selection: "ev, source, nsig: (ev.MTW(ev, source, nsig) >= 30.) & (ev.MTW(ev, source, nsig) < 125.)"
    mll_selection: "ev, source, nsig: (ev.MLL(ev, source, nsig) >= 71.) & (ev.MLL(ev, source, nsig) < 111.)"
    met_pf_selection: "ev, source, nsig: ev.MET_ptShift(ev, source, nsig) > 100."
    ngen_boson_selection:
        "ev, source, nsig: np.ones(ev.size, dtype=bool)
             if ev.config.dataset.parent not in 'EWKV2Jets'
             else (ev.nGenBosons(ev)==1)"
grouped_selections:
    data:
        - "lumi_selection"
#        - "trigger_selection"
    mc:
        - "ngen_boson_selection"
    baseline:
        - "filter_selection"
        - "met_selection"
        - "dcalo_pfmet_selection"
        - "jet_selection"
        - "lead_jet_selection"
    vbaseline:
        - "pho_0_selection"
        - "bjet_0_selection"
    monojet:
        - "dphi_jet_met_selection"
    monojetqcd:
        - "dphi_jet_met_inv_selection"
    vmonojet:
        - "muon_0_selection"
        - "ele_0_selection"
        - "tau_0_selection"
    singlemuon:
        - "dphi_jet_met_selection"
        - "muon_1_selection"
        - "mtw_selection"
    vmuon:
        - "ele_0_selection"
        - "tau_0_selection"
    singlemuonqcd:
        - "dphi_jet_met_inv_selection"
        - "muon_1_selection"
        - "mtw_selection"
    singlemuonplus:
        - "lepton_p1_charge"
    singlemuonminus:
        - "lepton_m1_charge"
    doublemuon:
        - "dphi_jet_met_selection"
        - "muon_2_selection"
        - "mll_selection"
        - "lepton_zero_charge"
    triplemuon:
        - "dphi_jet_met_selection"
        - "muon_3_selection"
    singleelectron:
        - "dphi_jet_met_selection"
        - "ele_1_selection"
        - "mtw_selection"
        - "met_pf_selection"
    velectron:
        - "muon_0_selection"
        - "tau_0_selection"
    singleelectronqcd:
        - "dphi_jet_met_inv_selection"
        - "ele_1_selection"
        - "mtw_selection"
        - "met_pf_selection"
    singleelectronplus:
        - "lepton_p1_charge"
    singleelectronminus:
        - "lepton_m1_charge"
    doubleelectron:
        - "dphi_jet_met_selection"
        - "ele_2_selection"
        - "mll_selection"
        - "lepton_zero_charge"
    doubleelectronalt:
        - "filter_selection"
        - "met_low_selection"
        - "jet_selection"
        - "ele_2_selection"
        - "lepton_zero_charge"
    tripleelectron:
        - "dphi_jet_met_selection"
        - "ele_3_selection"
    singletau:
        - "dphi_jet_met_selection"
        - "tau_1_selection"
    vtau:
        - "muon_0_selection"
        - "ele_0_selection"
cutflows:
    None:
        Data: []
        MC: []
    Monojet:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "monojet"
            - "vmonojet"
        MC:
            - "mc"
            - "baseline"
            - "monojet"
    MonojetQCD:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "monojetqcd"
            - "vmonojet"
        MC:
            - "mc"
            - "baseline"
            - "monojetqcd"
    SingleMuon:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "singlemuon"
            - "vmuon"
        MC:
            - "mc"
            - "baseline"
            - "singlemuon"
    SingleMuonQCD:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "singlemuonqcd"
            - "vmuon"
        MC:
            - "mc"
            - "baseline"
            - "singlemuonqcd"
    SingleMuonPlus:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "singlemuonplus"
            - "vmuon"
        MC:
            - "mc"
            - "baseline"
            - "singlemuonplus"
    SingleMuonMinus:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "singlemuonminus"
            - "vmuon"
        MC:
            - "mc"
            - "baseline"
            - "singlemuonminus"
    DoubleMuon:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "doublemuon"
            - "vmuon"
        MC:
            - "mc"
            - "baseline"
            - "doublemuon"
    TripleMuon:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "triplemuon"
            - "vmuon"
        MC:
            - "mc"
            - "baseline"
            - "triplemuon"
    SingleElectron:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "singleelectron"
            - "velectron"
        MC:
            - "mc"
            - "baseline"
            - "singleelectron"
    SingleElectronQCD:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "singleelectronqcd"
            - "velectron"
        MC:
            - "mc"
            - "baseline"
            - "singleelectronqcd"
    SingleElectronPlus:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "singleelectron"
            - "singleelectronplus"
            - "velectron"
        MC:
            - "mc"
            - "baseline"
            - "singleelectron"
            - "singleelectronplus"
    SingleElectronMinus:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "singleelectron"
            - "singleelectronminus"
            - "velectron"
        MC:
            - "mc"
            - "baseline"
            - "singleelectron"
            - "singleelectronminus"
    DoubleElectron:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "doubleelectron"
            - "velectron"
        MC:
            - "mc"
            - "baseline"
            - "doubleelectron"
    DoubleElectronAlt:
        Data:
            - "data"
            - "doubleelectronalt"
        MC:
            - "mc"
            - "doubleelectronalt"
    TripleElectron:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "tripleelectron"
            - "velectron"
        MC:
            - "mc"
            - "baseline"
            - "tripleelectron"
    SingleTau:
        Data:
            - "data"
            - "baseline"
            - "vbaseline"
            - "singletau"
            - "vtau"
        MC:
            - "mc"
            - "baseline"
            - "singletau"
