name: "Events"
output: "/vols/cms/sdb15/database_outputs/"
variations: []
attributes:
    Both:
        run: "ev, source, nsig: ev.run"
        luminosityBlock: "ev, source, nsig: ev.luminosityBlock"
        event: "ev, source, nsig: ev.event"
        isdata: "ev, source, nsig: np.full(ev.size, ev.config.dataset.isdata, dtype=np.bool8)"
        parent: "ev, source, nsig: np.full(ev.size, ev.config.dataset.parent)"
        sample: "ev, source, nsig: np.full(ev.size, ev.config.dataset.name)"
    MC:
        nGenBosonSelection: "ev, source, nsig: ev.nGenBosons(ev)"
        GenPartBoson_pt: "ev, source, nsig: ev.GenPartBoson(ev, 'pt')"
        GenPartBoson_eta: "ev, source, nsig: ev.GenPartBoson(ev, 'eta')"
        GenPartBoson_phi: "ev, source, nsig: ev.GenPartBoson(ev, 'phi')"
        GenPartBoson_mass: "ev, source, nsig: ev.GenPartBoson(ev, 'mass')"
        Pileup_nPU: "ev, source, nsig: ev.Pileup_nPU"
        Pileup_nTrueInt: "ev, source, nsig: ev.Pileup_nTrueInt"
        LeptonIsElectron: "ev, source, nsig: ev.LeptonIs(ev, 'Electron')"
        LeptonIsMuon: "ev, source, nsig: ev.LeptonIs(ev, 'Muon')"
        LeptonIsTau: "ev, source, nsig: ev.LeptonIs(ev, 'Tau')"
        nGenTauL: "ev, source, nsig: ev.nGenTauL(ev)"
        genWeight: "ev, source, nsig: ev.genWeight"
        WeightXsLumi: "ev, source, nsig: ev.WeightXsLumi(ev)"
        K_NLOQCD_NLOQCDnNLOEWK: "ev, source, nsig: ev.K_NLOQCD_NLOQCDnNLOEWK(ev, source, nsig)"
        K_NLOQCD_NNLOQCD: "ev, source, nsig: ev.K_NLOQCD_NNLOQCD(ev, source, nsig)"
        K_NLOQCD_NNLOQCDnNLOEWK: "ev, source, nsig: ev.K_NLOQCD_NNLOQCDnNLOEWK(ev, source, nsig)"
        WeightPU: "ev, source, nsig: ev.WeightPU(ev, source, nsig)"
        WeightPU_pileupUp: "ev, source, nsig: ev.WeightPU(ev, 'pileup', 1.)"
        WeightPU_pileupDown: "ev, source, nsig: ev.WeightPU(ev, 'pileup', -1.)"
        Generator_id1: "ev, source, nsig: ev.Generator_id1"
        Generator_id2: "ev, source, nsig: ev.Generator_id2"
        Generator_x1: "ev, source, nsig: ev.Generator_x1"
        Generator_x2: "ev, source, nsig: ev.Generator_x2"
    Data:
        IsCertified: "ev, source, nsig: ev.IsCertified(ev)"
dtypes:
    run: "int64"
    luminosityBlock: "int64"
    event: "int64"
    isdata: "bool"
    parent: "str"
    sample: "str"
    METnoX_pt: "float64"
    METnoX_phi: "float64"
    METnoX_sumEt: "float64"
    MET_pt: "float64"
    MET_phi: "float64"
    MET_sumEt: "float64"
    MET_dCaloMET: "float64"
    CaloMET_pt: "float64"
    CaloMET_phi: "float64"
    CaloMET_sumEt: "float64"
    PuppiMET_pt: "float64"
    PuppiMET_phi: "float64"
    PuppiMETnoX_pt: "float64"
    PuppiMETnoX_phi: "float64"
    MinDPhiJ1234METnoX: "float64"
    MinDPhiJ1234PuppiMETnoX: "float64"
    MTW: "float64"
    MLL: "float64"
    nJetVeto: "int64"
    nJetSelection: "int64"
    LeadJetSelection_pt: "float64"
    LeadJetSelection_eta: "float64"
    LeadJetSelection_phi: "float64"
    LeadJetSelection_chEmEF: "float64"
    LeadJetSelection_chHEF: "float64"
    LeadJetSelection_neEmEF: "float64"
    LeadJetSelection_neHEF: "float64"
    LeadJetSelection_dphiMET: "float64"
    LeadJetSelection_dphiPuppiMET: "float64"
    LeadJetFwdSelection_pt: "float64"
    LeadJetFwdSelection_eta: "float64"
    LeadJetFwdSelection_phi: "float64"
    LeadJetFwdSelection_dphiMET: "float64"
    LeadJetFwdSelection_dphiPuppiMET: "float64"
    NearestJetSelectionMET_pt: "float64"
    NearestJetSelectionMET_eta: "float64"
    NearestJetSelectionMET_phi: "float64"
    NearestJetSelectionMET_dphiMET: "float64"
    NearestJetSelectionPuppiMET_pt: "float64"
    NearestJetSelectionPuppiMET_eta: "float64"
    NearestJetSelectionPuppiMET_phi: "float64"
    NearestJetSelectionPuppiMET_dphiPuppiMET: "float64"
    SecondJetSelection_pt: "float64"
    SecondJetSelection_eta: "float64"
    SecondJetSelection_phi: "float64"
    SecondJetSelection_dphiMET: "float64"
    SecondJetSelection_dphiPuppiMET: "float64"
    nMuonVeto: "int64"
    nMuonSelection: "int64"
    LeadMuonSelection_pt: "float64"
    LeadMuonSelection_eta: "float64"
    LeadMuonSelection_phi: "float64"
    LeadMuonSelection_dRTrigMuon: "float64"
    SecondMuonSelection_pt: "float64"
    SecondMuonSelection_eta: "float64"
    SecondMuonSelection_phi: "float64"
    SecondMuonSelection_dRTrigMuon: "float64"
    ThirdMuonSelection_pt: "float64"
    ThirdMuonSelection_eta: "float64"
    ThirdMuonSelection_phi: "float64"
    ThirdMuonSelection_dRTrigMuon: "float64"
    nElectronVeto: "int64"
    nElectronSelection: "int64"
    LeadElectronSelection_pt: "float64"
    LeadElectronSelection_eta: "float64"
    LeadElectronSelection_phi: "float64"
    LeadElectronSelection_dRTrigElectron: "float64"
    SecondElectronSelection_pt: "float64"
    SecondElectronSelection_eta: "float64"
    SecondElectronSelection_phi: "float64"
    SecondElectronSelection_dRTrigElectron: "float64"
    nTauVeto: "int64"
    nTauSelection: "int64"
    LeadTauSelection_pt: "float64"
    LeadTauSelection_eta: "float64"
    LeadTauSelection_phi: "float64"
    LeadTauSelection_dphiMET: "float64"
    LeadTauSelection_dphiPuppiMET: "float64"
    nIsoTrack: "int64"
    LeadIsoTrack_pt: "float64"
    LeadIsoTrack_eta: "float64"
    LeadIsoTrack_phi: "float64"
    LeadIsoTrack_pdgId: "float64"
    nPhotonVeto: "int64"
    nPhotonSelection: "int64"
    nBJetVeto: "int64"
    PV_npvsGood: "int64"
    LeptonCharge: "int64"
    #IsMETTriggered: "bool"
    #IsSingleMuonTriggered: "bool"
    #IsSingleElectronTriggered: "bool"
    HLT_PFMETNoMu90_PFMHTNoMu90_IDTight: "bool"
    HLT_PFMETNoMu100_PFMHTNoMu100_IDTight: "bool"
    HLT_PFMETNoMu110_PFMHTNoMu110_IDTight: "bool"
    HLT_PFMETNoMu120_PFMHTNoMu120_IDTight: "bool"
    HLT_PFMET170_NotCleaned: "bool"
    HLT_PFMET170_BeamHaloCleaned: "bool"
    HLT_PFMET170_HBHECleaned: "bool"
    HLT_PFMET170_HBHE_BeamHaloCleaned: "bool"
    HLT_PFMET170_JetIdCleaned: "bool"
    HLT_PFMET170_NoiseCleaned: "bool"
    HLT_PFMET90_PFMHT90_IDTight: "bool"
    HLT_PFMET100_PFMHT100_IDTight: "bool"
    HLT_PFMET100_PFMHT100_IDTight_BeamHaloCleaned: "bool"
    HLT_PFMET110_PFMHT110_IDTight: "bool"
    HLT_PFMET120_PFMHT120_IDTight: "bool"
    HLT_MET75_IsoTrk50: "bool"
    HLT_MET200: "bool"
    HLT_IsoMu24: "bool"
    HLT_IsoTkMu24: "bool"
    HLT_Mu50: "bool"
    HLT_TkMu50: "bool"
    HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL: "bool"
    HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL: "bool"
    HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ: "bool"
    HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ: "bool"
    HLT_Ele25_eta2p1_WPTight_Gsf: "bool"
    HLT_Ele27_WPTight_Gsf: "bool"
    HLT_Ele115_CaloIdVT_GsfTrkIdT: "bool"
    HLT_Photon175: "bool"
    HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ: "bool"
    HLT_DoubleEle33_CaloIdL_MW: "bool"
    HLT_DoubleEle33_CaloIdL_GsfTrkIdVL: "bool"
    HLT_DoublePhoton60: "bool"
    Flag_goodVertices: "bool"
    Flag_globalSuperTightHalo2016Filter: "bool"
    Flag_HBHENoiseFilter: "bool"
    Flag_HBHENoiseIsoFilter: "bool"
    Flag_EcalDeadCellTriggerPrimitiveFilter: "bool"
    Flag_BadPFMuonFilter: "bool"
    #Flag_BadGlobalMuon: "bool"
    #Flag_CloneGlobalMuon: "bool"
    Flag_eeBadScFilter: "bool"
    nGenBosonSelection: "int64"
    GenPartBoson_pt: "float64"
    GenPartBoson_eta: "float64"
    GenPartBoson_phi: "float64"
    GenPartBoson_mass: "float64"
    LeadGenLepCandidate_pdgId: "float64"
    LeadGenLepCandidate_pt: "float64"
    LeadGenLepCandidate_eta: "float64"
    LeadGenLepCandidate_phi: "float64"
    LeadGenLepCandidate_mass: "float64"
    SecondGenLepCandidate_pdgId: "float64"
    SecondGenLepCandidate_pt: "float64"
    SecondGenLepCandidate_eta: "float64"
    SecondGenLepCandidate_phi: "float64"
    SecondGenLepCandidate_mass: "float64"
    Pileup_nPU: "int64"
    Pileup_nTrueInt: "int64"
    LeptonIsElectron: "bool"
    LeptonIsMuon: "bool"
    LeptonIsTau: "bool"
    nGenTauL: "int64"
    genWeight: "float64"
    WeightXsLumi: "float64"
    K_NLOQCD_NLOQCDnNLOEWK: "float64"
    K_NLOQCD_NNLOQCD: "float64"
    K_NLOQCD_NNLOQCDnNLOEWK: "float64"
    WeightQcdEwk: "float64"
    WeightQcdEwk_d1kqcdUp: "float64"
    WeightQcdEwk_d1kqcdDown: "float64"
    WeightQcdEwk_d2kqcdUp: "float64"
    WeightQcdEwk_d2kqcdDown: "float64"
    WeightQcdEwk_d3kqcdUp: "float64"
    WeightQcdEwk_d3kqcdDown: "float64"
    WeightQcdEwk_d1kewUp: "float64"
    WeightQcdEwk_d1kewDown: "float64"
    WeightQcdEwk_d2kewzUp: "float64"
    WeightQcdEwk_d2kewzDown: "float64"
    WeightQcdEwk_d2kewwUp: "float64"
    WeightQcdEwk_d2kewwDown: "float64"
    WeightQcdEwk_d3kewzUp: "float64"
    WeightQcdEwk_d3kewzDown: "float64"
    WeightQcdEwk_d3kewwUp: "float64"
    WeightQcdEwk_d3kewwDown: "float64"
    WeightQcdEwk_dkmixUp: "float64"
    WeightQcdEwk_dkmixDown: "float64"
    WeightPU: "float64"
    WeightPU_pileupUp: "float64"
    WeightPU_pileupDown: "float64"
    WeightPreFiring: "float64"
    WeightPreFiring_prefiringUp: "float64"
    WeightPreFiring_prefiringDown: "float64"
    WeightMETTrig: "float64"
    WeightMETTrig_muonMultiplicitySystUp: "float64"
    WeightMETTrig_muonMultiplicitySystDown: "float64"
    WeightMETTrig_referenceTriggerSystUp: "float64"
    WeightMETTrig_referenceTriggerSystDown: "float64"
    WeightMETTrig_regionSystUp: "float64"
    WeightMETTrig_regionSystDown: "float64"
    WeightSingleMuonTrig: "float64"
    WeightSingleMuonTrig_muonTrigUp: "float64"
    WeightSingleMuonTrig_muonTrigDown: "float64"
    WeightSingleElectronTrig: "float64"
    WeightSingleElectronTrig_eleTrigUp: "float64"
    WeightSingleElectronTrig_eleTrigDown: "float64"
    WeightOneMinusElectronVetoNoSelectionIdIsoVeto: "float64"
    WeightOneMinusElectronVetoNoSelectionIdIsoVeto_eleIdIsoVetoUp: "float64"
    WeightOneMinusElectronVetoNoSelectionIdIsoVeto_eleIdIsoVetoDown: "float64"
    WeightOneMinusElectronSelectionIdIsoTight: "float64"
    WeightOneMinusElectronSelectionIdIsoTight_eleIdIsoTightUp: "float64"
    WeightOneMinusElectronSelectionIdIsoTight_eleIdIsoTightDown: "float64"
    WeightOneMinusElectronVetoReco: "float64"
    WeightOneMinusElectronVetoReco_eleRecoUp: "float64"
    WeightOneMinusElectronVetoReco_eleRecoDown: "float64"
    WeightOneMinusElectronVetoNoSelectionReco: "float64"
    WeightOneMinusElectronVetoNoSelectionReco_eleRecoUp: "float64"
    WeightOneMinusElectronVetoNoSelectionReco_eleRecoDown: "float64"
    WeightOneMinusMuonVetoNoSelectionIdLoose: "float64"
    WeightOneMinusMuonVetoNoSelectionIdLoose_muonIdLooseStatUp: "float64"
    WeightOneMinusMuonVetoNoSelectionIdLoose_muonIdLooseStatDown: "float64"
    WeightOneMinusMuonVetoNoSelectionIdLoose_muonIdLooseSystUp: "float64"
    WeightOneMinusMuonVetoNoSelectionIdLoose_muonIdLooseSystDown: "float64"
    WeightOneMinusMuonVetoNoSelectionIsoLoose: "float64"
    WeightOneMinusMuonVetoNoSelectionIsoLoose_muonIsoLooseStatUp: "float64"
    WeightOneMinusMuonVetoNoSelectionIsoLoose_muonIsoLooseStatDown: "float64"
    WeightOneMinusMuonVetoNoSelectionIsoLoose_muonIsoLooseSystUp: "float64"
    WeightOneMinusMuonVetoNoSelectionIsoLoose_muonIsoLooseSystDown: "float64"
    WeightOneMinusMuonSelectionIdTight: "float64"
    WeightOneMinusMuonSelectionIdTight_muonIdTightStatUp: "float64"
    WeightOneMinusMuonSelectionIdTight_muonIdTightStatDown: "float64"
    WeightOneMinusMuonSelectionIdTight_muonIdTightSystUp: "float64"
    WeightOneMinusMuonSelectionIdTight_muonIdTightSystDown: "float64"
    WeightOneMinusMuonSelectionIsoTight: "float64"
    WeightOneMinusMuonSelectionIsoTight_muonIsoTightStatUp: "float64"
    WeightOneMinusMuonSelectionIsoTight_muonIsoTightStatDown: "float64"
    WeightOneMinusMuonSelectionIsoTight_muonIsoTightSystUp: "float64"
    WeightOneMinusMuonSelectionIsoTight_muonIsoTightSystDown: "float64"
    WeightOneMinusPhotonVetoIdLoose: "float64"
    WeightOneMinusPhotonVetoIdLoose_photonIdLooseUp: "float64"
    WeightOneMinusPhotonVetoIdLoose_photonIdLooseDown: "float64"
    WeightOneMinusPhotonVetoPixelSeedVeto: "float64"
    WeightOneMinusPhotonVetoPixelSeedVeto_photonPixelSeedVetoUp: "float64"
    WeightOneMinusPhotonVetoPixelSeedVeto_photonPixelSeedVetoDown: "float64"
    WeightOneMinusTauSelectionIdTight: "float64"
    WeightOneMinusTauSelectionIdTight_tauIdTightUp: "float64"
    WeightOneMinusTauSelectionIdTight_tauIdTightDown: "float64"
    WeightOneMinusTauVetoNoSelectionIdVLoose: "float64"
    WeightOneMinusTauVetoNoSelectionIdVLoose_tauIdVLooseUp: "float64"
    WeightOneMinusTauVetoNoSelectionIdVLoose_tauIdVLooseDown: "float64"
    WeightOneMinusJetBVetoIdMedium: "float64"
    WeightOneMinusJetBVetoIdMedium_btagSFUp: "float64"
    WeightOneMinusJetBVetoIdMedium_btagSFDown: "float64"
    WeightMuonSelectionIdTight: "float64"
    WeightMuonSelectionIdTight_muonIdTightStatUp: "float64"
    WeightMuonSelectionIdTight_muonIdTightStatDown: "float64"
    WeightMuonSelectionIdTight_muonIdTightSystUp: "float64"
    WeightMuonSelectionIdTight_muonIdTightSystDown: "float64"
    WeightMuonSelectionIsoTight: "float64"
    WeightMuonSelectionIsoTight_muonIsoTightStatUp: "float64"
    WeightMuonSelectionIsoTight_muonIsoTightStatDown: "float64"
    WeightMuonSelectionIsoTight_muonIsoTightSystUp: "float64"
    WeightMuonSelectionIsoTight_muonIsoTightSystDown: "float64"
    WeightTauSelectionIdTight: "float64"
    WeightTauSelectionIdTight_tauIdTightUp: "float64"
    WeightTauSelectionIdTight_tauIdTightDown: "float64"
    WeightElectronSelectionIdIsoTight: "float64"
    WeightElectronSelectionIdIsoTight_eleIdIsoTightUp: "float64"
    WeightElectronSelectionIdIsoTight_eleIdIsoTightDown: "float64"
    WeightElectronSelectionReco: "float64"
    WeightElectronSelectionReco_eleRecoUp: "float64"
    WeightElectronSelectionReco_eleRecoDown: "float64"
    Generator_id1: "int64"
    Generator_id2: "int64"
    Generator_x1: "float64"
    Generator_x2: "float64"
    nLHEScaleWeight: "int64"
    nLHEPdfWeight: "int64"
    LHEScaleWeight0: "float64"
    LHEScaleWeight1: "float64"
    LHEScaleWeight2: "float64"
    LHEScaleWeight3: "float64"
    LHEScaleWeight4: "float64"
    LHEScaleWeight5: "float64"
    LHEScaleWeight6: "float64"
    LHEScaleWeight7: "float64"
    LHEScaleWeight8: "float64"
    LHEPdfWeight0: "float64"
    LHEPdfWeight1: "float64"
    LHEPdfWeight2: "float64"
    LHEPdfWeight3: "float64"
    LHEPdfWeight4: "float64"
    LHEPdfWeight5: "float64"
    LHEPdfWeight6: "float64"
    LHEPdfWeight7: "float64"
    LHEPdfWeight8: "float64"
    LHEPdfWeight9: "float64"
    LHEPdfWeight10: "float64"
    LHEPdfWeight11: "float64"
    LHEPdfWeight12: "float64"
    LHEPdfWeight13: "float64"
    LHEPdfWeight14: "float64"
    LHEPdfWeight15: "float64"
    LHEPdfWeight16: "float64"
    LHEPdfWeight17: "float64"
    LHEPdfWeight18: "float64"
    LHEPdfWeight19: "float64"
    LHEPdfWeight20: "float64"
    LHEPdfWeight21: "float64"
    LHEPdfWeight22: "float64"
    LHEPdfWeight23: "float64"
    LHEPdfWeight24: "float64"
    LHEPdfWeight25: "float64"
    LHEPdfWeight26: "float64"
    LHEPdfWeight27: "float64"
    LHEPdfWeight28: "float64"
    LHEPdfWeight29: "float64"
    LHEPdfWeight30: "float64"
    LHEPdfWeight31: "float64"
    LHEPdfWeight32: "float64"
    LHEPdfWeight33: "float64"
    LHEPdfWeight34: "float64"
    LHEPdfWeight35: "float64"
    LHEPdfWeight36: "float64"
    LHEPdfWeight37: "float64"
    LHEPdfWeight38: "float64"
    LHEPdfWeight39: "float64"
    LHEPdfWeight40: "float64"
    LHEPdfWeight41: "float64"
    LHEPdfWeight42: "float64"
    LHEPdfWeight43: "float64"
    LHEPdfWeight44: "float64"
    LHEPdfWeight45: "float64"
    LHEPdfWeight46: "float64"
    LHEPdfWeight47: "float64"
    LHEPdfWeight48: "float64"
    LHEPdfWeight49: "float64"
    LHEPdfWeight50: "float64"
    LHEPdfWeight51: "float64"
    LHEPdfWeight52: "float64"
    LHEPdfWeight53: "float64"
    LHEPdfWeight54: "float64"
    LHEPdfWeight55: "float64"
    LHEPdfWeight56: "float64"
    LHEPdfWeight57: "float64"
    LHEPdfWeight58: "float64"
    LHEPdfWeight59: "float64"
    LHEPdfWeight60: "float64"
    LHEPdfWeight61: "float64"
    LHEPdfWeight62: "float64"
    LHEPdfWeight63: "float64"
    LHEPdfWeight64: "float64"
    LHEPdfWeight65: "float64"
    LHEPdfWeight66: "float64"
    LHEPdfWeight67: "float64"
    LHEPdfWeight68: "float64"
    LHEPdfWeight69: "float64"
    LHEPdfWeight70: "float64"
    LHEPdfWeight71: "float64"
    LHEPdfWeight72: "float64"
    LHEPdfWeight73: "float64"
    LHEPdfWeight74: "float64"
    LHEPdfWeight75: "float64"
    LHEPdfWeight76: "float64"
    LHEPdfWeight77: "float64"
    LHEPdfWeight78: "float64"
    LHEPdfWeight79: "float64"
    LHEPdfWeight80: "float64"
    LHEPdfWeight81: "float64"
    LHEPdfWeight82: "float64"
    LHEPdfWeight83: "float64"
    LHEPdfWeight84: "float64"
    LHEPdfWeight85: "float64"
    LHEPdfWeight86: "float64"
    LHEPdfWeight87: "float64"
    LHEPdfWeight88: "float64"
    LHEPdfWeight89: "float64"
    LHEPdfWeight90: "float64"
    LHEPdfWeight91: "float64"
    LHEPdfWeight92: "float64"
    LHEPdfWeight93: "float64"
    LHEPdfWeight94: "float64"
    LHEPdfWeight95: "float64"
    LHEPdfWeight96: "float64"
    LHEPdfWeight97: "float64"
    LHEPdfWeight98: "float64"
    LHEPdfWeight99: "float64"
    LHEPdfWeight100: "float64"
    LHEPdfWeight101: "float64"
    LHEPdfWeight102: "float64"
    LHEPdfWeight103: "float64"
    IsCertified: "bool"
