sequence:
    - name: "event_tools"
      module: "zinv.modules.readers.EventTools"
      args:
          maxsize: 8
    - name: "collection_creator"
      module: "zinv.modules.readers.CollectionCreator"
      args:
          collections: [
              "CaloMET", "MET", "PuppiMET", "Jet", "Electron", "Muon", "Photon",
              "Tau", "IsoTrack", "TrigObj", "GenMET", "GenPart", "GenJet",
              "GenDressedLepton", "LHEPart",
          ]
    - name: "gen_boson_producer"
      module: "zinv.modules.readers.GenBosonProducer"
      args:
          data: False
    - name: "lhe_part_assigner"
      module: "zinv.modules.readers.LHEPartAssigner"
      args:
          old_parents: ["WJetsToLNu", "DYJetsToLL", "ZJetsToLL", "GStarJetsToLL"]
          data: False
    - name: "gen_part_assigner"
      module: "zinv.modules.readers.GenPartAssigner"
      args:
          old_parents: ["WJetsToLNu", "DYJetsToLL", "ZJetsToLL", "GStarJetsToLL"]
          data: False
    - name: "weight_xsection_lumi"
      module: "zinv.modules.readers.WeightXsLumi"
      args:
          data: False
    - name: "weight_pu"
      module: "zinv.modules.readers.WeightPileup"
      args:
          correction_file: "http://www.hep.ph.ic.ac.uk/~sdb15/Analysis/ZinvWidth/data/pileup/nTrueInt_corrections.txt"
          variable: "Pileup_nTrueInt"
          data: False
    - name: "weight_qcd_ewk_K_NLOQCD_NNLOQCDnNLOEWK"
      module: "zinv.modules.readers.WeightQcdEwk"
      args:
          label: "K_NLOQCD_NNLOQCDnNLOEWK"
          input_paths:
              ZJetsToNuNu: ["http://www.hep.ph.ic.ac.uk/~sdb15/Analysis/ZinvWidth/data/qcd_ewk/vvj.dat", "vvj_pTV_{}"]
              WJetsToLNu: ["http://www.hep.ph.ic.ac.uk/~sdb15/Analysis/ZinvWidth/data/qcd_ewk/evj.dat", "evj_pTV_{}"]
              DYJetsToLL: ["http://www.hep.ph.ic.ac.uk/~sdb15/Analysis/ZinvWidth/data/qcd_ewk/eej.dat", "eej_pTV_{}"]
          underflow: True
          overflow: True
          formula: "((K_NNLO + d1k_qcd*d1K_NNLO + d2k_qcd*d2K_NNLO + d3k_qcd*d3K_NNLO)*(1 + kappa_EW + d1k_ew*d1kappa_EW + isz*(d2k_ew_z*d2kappa_EW + d3k_ew_z*d3kappa_EW) + isw*(d2k_ew_w*d2kappa_EW + d3k_ew_w*d3kappa_EW)) + dk_mix*dK_NNLO_mix)/(K_NLO + d1k_qcd*d1K_NLO + d2k_qcd*d2K_NLO + d3k_qcd*d3K_NLO)"
          params: [
              "K_NLO", "d1K_NLO", "d2K_NLO", "d3K_NLO", "K_NNLO", "d1K_NNLO",
              "d2K_NNLO", "d3K_NNLO", "kappa_EW", "d1kappa_EW", "d2kappa_EW",
              "d3kappa_EW", "dK_NNLO_mix",
          ]
          variation_names: [
              "d1k_qcd", "d2k_qcd", "d3k_qcd", "d1k_ew", "d2k_ew_z", "d2k_ew_w",
              "d3k_ew_z", "d3k_ew_w", "dk_mix",
          ]
          data: False
    - name: "weight_qcd_ewk_K_NLOQCD_NNLOQCD"
      module: "zinv.modules.readers.WeightQcdEwk"
      args:
          label: "K_NLOQCD_NNLOQCD"
          input_paths:
              ZJetsToNuNu: ["http://www.hep.ph.ic.ac.uk/~sdb15/Analysis/ZinvWidth/data/qcd_ewk/vvj.dat", "vvj_pTV_{}"]
              WJetsToLNu: ["http://www.hep.ph.ic.ac.uk/~sdb15/Analysis/ZinvWidth/data/qcd_ewk/evj.dat", "evj_pTV_{}"]
              DYJetsToLL: ["http://www.hep.ph.ic.ac.uk/~sdb15/Analysis/ZinvWidth/data/qcd_ewk/eej.dat", "eej_pTV_{}"]
          underflow: True
          overflow: True
          formula: "((K_NNLO + d1k_qcd*d1K_NNLO + d2k_qcd*d2K_NNLO + d3k_qcd*d3K_NNLO) + dk_mix*dK_NNLO_mix)/(K_NLO + d1k_qcd*d1K_NLO + d2k_qcd*d2K_NLO + d3k_qcd*d3K_NLO)"
          params: [
              "K_NLO", "d1K_NLO", "d2K_NLO", "d3K_NLO", "K_NNLO", "d1K_NNLO",
              "d2K_NNLO", "d3K_NNLO", "kappa_EW", "d1kappa_EW", "d2kappa_EW",
              "d3kappa_EW", "dK_NNLO_mix",
          ]
          variation_names: [
              "d1k_qcd", "d2k_qcd", "d3k_qcd", "d1k_ew", "d2k_ew_z", "d2k_ew_w",
              "d3k_ew_z", "d3k_ew_w", "dk_mix",
          ]
          data: False
    - name: "weight_qcd_ewk_K_NLOQCD_NLOQCDnNLOEWK"
      module: "zinv.modules.readers.WeightQcdEwk"
      args:
          label: "K_NLOQCD_NLOQCDnNLOEWK"
          input_paths:
              ZJetsToNuNu: ["http://www.hep.ph.ic.ac.uk/~sdb15/Analysis/ZinvWidth/data/qcd_ewk/vvj.dat", "vvj_pTV_{}"]
              WJetsToLNu: ["http://www.hep.ph.ic.ac.uk/~sdb15/Analysis/ZinvWidth/data/qcd_ewk/evj.dat", "evj_pTV_{}"]
              DYJetsToLL: ["http://www.hep.ph.ic.ac.uk/~sdb15/Analysis/ZinvWidth/data/qcd_ewk/eej.dat", "eej_pTV_{}"]
          underflow: True
          overflow: True
          formula: "((1 + kappa_EW + d1k_ew*d1kappa_EW + isz*(d2k_ew_z*d2kappa_EW + d3k_ew_z*d3kappa_EW) + isw*(d2k_ew_w*d2kappa_EW + d3k_ew_w*d3kappa_EW)) + dk_mix*dK_NNLO_mix)"
          params: [
              "K_NLO", "d1K_NLO", "d2K_NLO", "d3K_NLO", "K_NNLO", "d1K_NNLO",
              "d2K_NNLO", "d3K_NNLO", "kappa_EW", "d1kappa_EW", "d2kappa_EW",
              "d3kappa_EW", "dK_NNLO_mix",
          ]
          variation_names: [
              "d1k_qcd", "d2k_qcd", "d3k_qcd", "d1k_ew", "d2k_ew_z", "d2k_ew_w",
              "d3k_ew_z", "d3k_ew_w", "dk_mix",
          ]
          data: False
    - name: "hdf5_reader"
      module: "zinv.modules.collectors.HDF5Reader"
      args:
          measure_timing: True
