JetVeto:
    original: "Jet"
    selections:
        - "ev, source, nsig: ev.Jet_ptShift(ev, source, nsig)>40"
        - "ev, source, nsig: ev.Jet.jetId>=1"
JetSelection:
    original: "Jet"
    selections:
        - "ev, source, nsig: ev.Jet_ptShift(ev, source, nsig)>40"
        - "ev, source, nsig: np.abs(ev.Jet.eta)<2.4"
        - "ev, source, nsig: ev.Jet.jetId>=1"
JetFwdSelection:
    original: "Jet"
    selections:
        - "ev, source, nsig: np.abs(ev.Jet.eta)>=2.4"
        - "ev, source, nsig: ev.Jet.jetId>=1"
JetBVeto:
    original: "Jet"
    selections:
        - "ev, source, nsig: ev.Jet_ptShift(ev, source, nsig)>40"
        - "ev, source, nsig: ev.Jet.jetId>=1"
        - "ev, source, nsig: ev.Jet.btagCSVV2>0.8484"
JetBSelection:
    original: "Jet"
    selections:
        - "ev, source, nsig: ev.Jet_ptShift(ev, source, nsig)>40"
        - "ev, source, nsig: np.abs(ev.Jet.eta)<2.4"
        - "ev, source, nsig: ev.Jet.jetId>=1"
        - "ev, source, nsig: ev.Jet.btagCSVV2>0.8484"
MuonVeto:
    original: "Muon"
    selections:
        - "ev, source, nsig: ev.Muon_ptShift(ev, source, nsig)>10."
        - "ev, source, nsig: np.abs(ev.Muon.eta)<2.5"
        - "ev, source, nsig: np.abs(ev.Muon.pfRelIso04_all)<0.25"
        - "ev, source, nsig: np.abs(ev.Muon.dxy)<0.5"
        - "ev, source, nsig: np.abs(ev.Muon.dz)<1.0"
MuonSelection:
    original: "Muon"
    selections:
        - "ev, source, nsig: ev.Muon_ptShift(ev, source, nsig)>30."
        - "ev, source, nsig: np.abs(ev.Muon.eta)<2.4"
        - "ev, source, nsig: np.abs(ev.Muon.pfRelIso04_all)<0.15"
        - "ev, source, nsig: ev.Muon.tightId>=1"
ElectronVeto:
    original: "Electron"
    selections:
        - "ev, source, nsig: ev.Electron_ptShift(ev, source, nsig)>10."
        - "ev, source, nsig: np.abs(ev.Electron.eta)<2.5"
        - "ev, source, nsig: ev.Electron.cutBased>=1"
        - "ev, source, nsig: np.abs(ev.Electron.dxy)<0.118"
        - "ev, source, nsig: np.abs(ev.Electron.dz)<0.822"
        - "ev, source, nsig: ev.Electron.convVeto"
ElectronSelection:
    original: "Electron"
    selections:
        - "ev, source, nsig: ev.Electron_ptShift(ev, source, nsig)>30."
        - "ev, source, nsig: np.abs(ev.Electron.eta)<2.4"
        - "ev, source, nsig: ev.Electron.cutBased>=4"
        - "ev, source, nsig: ((np.abs(ev.Electron.eta)<=1.479) & (np.abs(ev.Electron.dxy)<0.05) & (np.abs(ev.Electron.dz)<0.1)) | ((np.abs(ev.Electron.eta)>1.479) & (np.abs(ev.Electron.dxy)<0.1) & (np.abs(ev.Electron.dz)<0.2))"
        - "ev, source, nsig: ev.Electron.convVeto"
PhotonVeto:
    original: "Photon"
    selections:
        - "ev, source, nsig: ev.Photon_ptShift(ev, source, nsig)>25."
        - "ev, source, nsig: np.abs(ev.Photon.eta)<2.5"
        - "ev, source, nsig: ev.Photon.cutBased>=1"
        - "ev, source, nsig: ~ev.Photon.pixelSeed"
PhotonSelection:
    original: "Photon"
    selections:
        - "ev, source, nsig: ev.Photon_ptShift(ev, source, nsig)>165."
        - "ev, source, nsig: np.abs(ev.Photon.eta)<1.45"
        - "ev, source, nsig: ev.Photon.cutBased>=3"
        - "ev, source, nsig: ~ev.Photon.pixelSeed"
TauVeto:
    original: "Tau"
    selections:
        - "ev, source, nsig: ev.Tau_ptShift(ev, source, nsig)>20."
        - "ev, source, nsig: np.abs(ev.Tau.eta)<2.3"
        - "ev, source, nsig: ev.Tau.idMVAoldDM>=1"
TauSelection:
    original: "Tau"
    selections:
        - "ev, source, nsig: ev.Tau_ptShift(ev, source, nsig)>40."
        - "ev, source, nsig: np.abs(ev.Tau.eta)<2.3"
        - "ev, source, nsig: ev.Tau.idMVAoldDM>=8"
