query:
    groupby:
    - table
    - varname0
    - varname1
    - varname2
    - selection
    - parent
    - binvar0
    - binvar1
    - binvar2
    tables:
        central: Events
    aliases: {}
    eval:
    -   METnoX_pt_bin: 'df: np.floor(df.METnoX_pt/5.)*5.'
    -   Generator_id1_bin: 'df: np.floor(df.Generator_id1/1.)*1.'
    -   Generator_id2_bin: 'df: np.floor(df.Generator_id2/1.)*1.'
    -   parent: 'df: np.where( df.parent.isin([''WJetsToLNu'', ''DYJetsToLL'']), np.where(
            df.parent==''WJetsToLNu'', np.where( df.LeptonCharge>0, np.where( df.LeptonIsElectron,
            np.full_like(df.parent, ''WJetsToEPlusNu''), np.where( df.LeptonIsMuon,
            np.full_like(df.parent, ''WJetsToMuPlusNu''), np.where( df.LeptonIsTau,
            np.where( df.nGenTauL==0, np.full_like(df.parent, ''WJetsToTauHPlusNu''),
            np.where( df.nGenTauL==1, np.full_like(df.parent, ''WJetsToTauLPlusNu''),
            np.full_like(df.parent, ''WJetsToTauPlusNu''), ), ), np.full_like(df.parent,
            ''WJetsToLPlusNu''), ), ), ), np.where( df.LeptonIsElectron, np.full_like(df.parent,
            ''WJetsToEMinusNu''), np.where( df.LeptonIsMuon, np.full_like(df.parent,
            ''WJetsToMuMinusNu''), np.where( df.LeptonIsTau, np.where( df.nGenTauL==0,
            np.full_like(df.parent, ''WJetsToTauHMinusNu''), np.where( df.nGenTauL==1,
            np.full_like(df.parent, ''WJetsToTauLMinusNu''), np.full_like(df.parent,
            ''WJetsToTauMinusNu''), ), ), np.full_like(df.parent, ''WJetsToLMinusNu''),
            ), ), ), ), np.where( df.parent==''DYJetsToLL'', np.where(  df.LeptonIsElectron,
            np.full_like(df.parent, ''DYJetsToEE''), np.where( df.LeptonIsMuon, np.full_like(df.parent,
            ''DYJetsToMuMu''), np.where( df.LeptonIsTau, np.where( df.nGenTauL==0,
            np.full_like(df.parent, ''DYJetsToTauHTauH''), np.where( df.nGenTauL==1,
            np.full_like(df.parent, ''DYJetsToTauHTauL''), np.where( df.nGenTauL==2,
            np.full_like(df.parent, ''DYJetsToTauLTauL''), np.full_like(df.parent,
            ''DYJetsToTauTau''), ), ), ), np.full_like(df.parent, ''DYJetsToLL''),
            ), ), ), df.parent, ), ), df.parent, )'
    -   Weight_MonojetInc: 'df: (df.WeightXsLumi)*(df.WeightQcdEwk)*(df.WeightPU)*(df.WeightPreFiring)*(df.WeightOneMinusPhotonVetoIdLoose)*(df.WeightOneMinusPhotonVetoPixelSeedVeto)*(df.WeightOneMinusJetBVetoIdMedium)*(df.WeightOneMinusElectronVetoNoSelectionIdIsoVeto)*(df.WeightOneMinusElectronSelectionIdIsoTight)*(df.WeightOneMinusElectronVetoReco)*(df.WeightOneMinusMuonVetoNoSelectionIdLoose)*(df.WeightOneMinusMuonVetoNoSelectionIsoLoose)*(df.WeightOneMinusMuonSelectionIdTight)*(df.WeightOneMinusMuonSelectionIsoTight)*(df.WeightOneMinusTauVetoNoSelectionIdVLoose)*(df.WeightMETTrig)'
    -   METTriggered: 'df: (df.HLT_PFMETNoMu90_PFMHTNoMu90_IDTight) | (df.HLT_PFMETNoMu100_PFMHTNoMu100_IDTight)
            | (df.HLT_PFMETNoMu110_PFMHTNoMu110_IDTight) | (df.HLT_PFMETNoMu120_PFMHTNoMu120_IDTight)
            | (df.HLT_PFMET170_NotCleaned) | (df.HLT_PFMET170_BeamHaloCleaned) | (df.HLT_PFMET170_HBHECleaned)
            | (df.HLT_PFMET170_HBHE_BeamHaloCleaned) | (df.HLT_MET75_IsoTrk50)'
    -   SingleMuonTriggered: 'df: (df.HLT_IsoMu24) | (df.HLT_IsoTkMu24)'
    -   SingleElectronTriggered: 'df: (df.HLT_Ele27_WPTight_Gsf) | (df.HLT_Ele115_CaloIdVT_GsfTrkIdT)'
    cutflows:
        MonojetInc:
            selection_name: MonojetInc
            selection: ((parent!='EWKV2Jets' | nGenBosonSelection==1)) & (Flag_goodVertices)
                & (Flag_globalSuperTightHalo2016Filter) & (Flag_HBHENoiseFilter) &
                (Flag_HBHENoiseIsoFilter) & (Flag_EcalDeadCellTriggerPrimitiveFilter)
                & (Flag_BadPFMuonFilter) & (MET_dCaloMET<0.5) & (nJetSelection>0)
                & (nJetSelection==nJetVeto) & (LeadJetSelection_chHEF>0.1) & (LeadJetSelection_neHEF<0.8)
                & (LeadJetSelection_pt>200.) & (METnoX_pt>200.) & (METTriggered) &
                (nTauSelection==0)
            weight: df.Weight_MonojetInc
            hists:
            - METnoX_pt_MinDPhiJ1234METnoX_NearestJetSelectionMET_pt
    hists:
        METnoX_pt_MinDPhiJ1234METnoX_NearestJetSelectionMET_pt:
        -   table: 'df: ''{table_name}'''
        -   varname0: 'df: ''METnoX_pt'''
        -   varname1: 'df: ''MinDPhiJ1234METnoX'''
        -   varname2: 'df: ''NearestJetSelectionMET_pt'''
        -   selection: 'df: ''{selection_name}'''
        -   parent: 'df: df.parent'
        -   binvar0: 'df: df.METnoX_pt_bin'
        -   binvar1: 'df: df.MinDPhiJ1234METnoX_bin'
        -   binvar2: 'df: df.NearestJetSelectionMET_pt_bin'
        -   count: 'df: 1.'
        -   sum_w: 'df: {weight}'
        -   sum_ww: 'df: df.sum_w**2'
files:
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00000.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00001.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00002.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00003.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00004.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00005.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00006.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00007.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00008-0.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00008-1.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00008-2.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00008-3.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00009-0.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00009-1.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00009-2.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00009-3.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00010.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00011.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00012.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00013.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00014.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00015.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00016.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00017.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00018.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00019.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00020.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00021.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00022.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00023.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00024.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00025-0.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00025-1.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00025-2.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00025-3.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00026-0.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00026-1.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00026-2.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00026-3.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00027.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00028.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00029.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00030.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00031.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00032.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00033.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00034.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00035.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00036-0.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00036-1.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00036-2.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00036-3.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00037.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00038.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00039.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00040.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00041.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00042.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00043.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00044.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00045.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00046.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00047.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00048.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00049.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00050.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00051.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00052.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00053.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00054.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00055.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00056.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00057.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00058.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00059.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00060.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00061.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00062.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00063.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00064.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00065.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00066.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00067.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00068.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00069.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00070.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00071.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00072.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00073.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00074.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00075.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00076.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00077.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00078.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00079.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00080.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00081-0.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00081-1.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00081-2.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00081-3.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00082-0.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00082-1.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00082-2.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00082-3.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00083.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00084.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00085.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00086.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00087.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00088.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00089.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00090.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00091.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00092.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00093.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00094.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00095.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00096.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00097.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00098.h5
- /vols/cms/sdb15/Analysis/ZinvWidth/databases/skims/2019/09_Sep/14_skims/mc/result_00099.h5
