Data:
    MET:
        B1:
            - 'HLT_PFMETNoMu90_PFMHTNoMu90_IDTight'
            - 'HLT_PFMETNoMu100_PFMHTNoMu100_IDTight'
            - 'HLT_PFMETNoMu110_PFMHTNoMu110_IDTight'
            - 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight'
            - 'HLT_PFMET170_NotCleaned'
            - 'HLT_PFMET170_BeamHaloCleaned'
            - 'HLT_PFMET170_HBHECleaned'
            - 'HLT_PFMET170_HBHE_BeamHaloCleaned'
        B2:
            - 'HLT_PFMETNoMu100_PFMHTNoMu100_IDTight'
            - 'HLT_PFMETNoMu110_PFMHTNoMu110_IDTight'
            - 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight'
            - 'HLT_PFMET170_NotCleaned'
            - 'HLT_PFMET170_BeamHaloCleaned'
            - 'HLT_PFMET170_HBHECleaned'
            - 'HLT_PFMET170_HBHE_BeamHaloCleaned'
        C1:
            - 'HLT_PFMETNoMu100_PFMHTNoMu100_IDTight'
            - 'HLT_PFMETNoMu110_PFMHTNoMu110_IDTight'
            - 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight'
            - 'HLT_PFMET170_HBHECleaned'
            - 'HLT_PFMET170_HBHE_BeamHaloCleaned'
        D1:
            - 'HLT_PFMETNoMu110_PFMHTNoMu110_IDTight'
            - 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight'
            - 'HLT_PFMET170_HBHECleaned'
            - 'HLT_PFMET170_HBHE_BeamHaloCleaned'
        E1:
            - 'HLT_PFMETNoMu110_PFMHTNoMu110_IDTight'
            - 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight'
            - 'HLT_PFMET170_HBHECleaned'
            - 'HLT_PFMET170_HBHE_BeamHaloCleaned'
        F1:
            - 'HLT_PFMETNoMu110_PFMHTNoMu110_IDTight'
            - 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight'
            - 'HLT_PFMET170_HBHECleaned'
            - 'HLT_PFMET170_HBHE_BeamHaloCleaned'
        G1:
            - 'HLT_PFMETNoMu110_PFMHTNoMu110_IDTight'
            - 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight'
            - 'HLT_PFMET170_HBHECleaned'
            - 'HLT_PFMET170_HBHE_BeamHaloCleaned'
        H2:
            - 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight'
            - 'HLT_PFMET170_HBHECleaned'
            - 'HLT_PFMET170_HBHE_BeamHaloCleaned'
        H3:
            - 'HLT_PFMETNoMu110_PFMHTNoMu110_IDTight'
            - 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight'
            - 'HLT_PFMET170_HBHECleaned'
            - 'HLT_PFMET170_HBHE_BeamHaloCleaned'
    SingleMuon:
        - 'HLT_IsoMu24'
        - 'HLT_IsoTkMu24'
    SingleElectron:
        - 'HLT_Ele27_WPTight_Gsf'
MC:
    MET:
        - 'HLT_PFMETNoMu120_PFMHTNoMu120_IDTight'
        - 'HLT_PFMET170_HBHECleaned'
        - 'HLT_PFMET170_HBHE_BeamHaloCleaned'
    SingleMuon:
        - 'HLT_IsoMu24'
        - 'HLT_IsoTkMu24'
    SingleElectron:
        - 'HLT_Ele27_WPTight_Gsf'
