METnoX_pt:
    binning:
    - 0.0
    - 1501.0
    - 50.0
    outpath: metnox_pt.pdf
    label: $\mathcal{U}$ (GeV)
METnoX_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: metnox_phi.pdf
    label: $\mathcal{U}_{\phi}$
METnoX_sumEt:
    binning:
    - 0.0
    - 5001.0
    - 250.0
    outpath: metnox_sumet.pdf
    label: $\mathcal{U}\ \sum E_{\mathrm{T}}$ (GeV)
MET_pt:
    binning:
    - 0.0
    - 1501.0
    - 50.0
    outpath: met_pt.pdf
    label: $p_{\mathrm{T}}^{\mathrm{miss}}$ (GeV)
MET_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: met_phi.pdf
    label: $p_{\mathrm{T},\phi}^{\mathrm{miss}}$
MET_sumEt:
    binning:
    - 0.0
    - 5001.0
    - 250.0
    outpath: met_sumet.pdf
    label: $p_{\mathrm{T}}^{\mathrm{miss}}\ \sum E_{\mathrm{T}}$ (GeV)
MET_dpt:
    binning:
    - -1.0
    - 1.001
    - 0.05
    outpath: met_dpt.pdf
    label: $p_{\mathrm{T}}^{\mathrm{miss}}\ \delta p_{\mathrm{T}}$
MET_dphi:
    binning:
    - -1.0
    - 1.001
    - 0.05
    outpath: met_dphi.pdf
    label: $p_{\mathrm{T}}^{\mathrm{miss}}\ \delta\phi$
CaloMET_pt:
    binning:
    - 0.0
    - 1500.1
    - 50.0
    outpath: calomet_pt.pdf
    label: $p_{\mathrm{T,calo}}^{\mathrm{miss}}$ (GeV)
CaloMET_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: calomet_phi.pdf
    label: $p_{\mathrm{T,calo}}^{\mathrm{miss}} \phi$
CaloMET_sumEt:
    binning:
    - 0.0
    - 5001.0
    - 250.0
    outpath: calomet_sumet.pdf
    label: $p_{\mathrm{T,calo}}^{\mathrm{miss}}\ \sum E_{\mathrm{T}}$ (GeV)
MET_dCaloMET:
    binning:
    - 0.0
    - 1.001
    - 0.02
    outpath: met_dcalomet.pdf
    label: $|p_{\mathrm{T}}^{\mathrm{miss}} - p_{\mathrm{T,calo}}^{\mathrm{miss}}|
        / \mathcal{U}$ (GeV)
PuppiMET_pt:
    binning:
    - 0.0
    - 1500.1
    - 50.0
    outpath: puppimet_pt.pdf
    label: $p_{\mathrm{T,puppi}}^{\mathrm{miss}}$ (GeV)
PuppiMET_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: puppimet_phi.pdf
    label: $p_{\mathrm{T,puppi},\phi}^{\mathrm{miss}}$ (GeV)
PuppiMETnoX_pt:
    binning:
    - 0.0
    - 1500.1
    - 50.0
    outpath: puppimetnox_pt.pdf
    label: $\mathcal{U}_{\mathrm{puppi}}$ (GeV)
PuppiMETnoX_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: puppimetnox_phi.pdf
    label: $\mathcal{U}_{\mathrm{puppi},\phi}$ (GeV)
MinDPhiJ1234METnoX:
    binning:
    - 0.0
    - 3.16
    - 0.05
    outpath: mindphij1234metnox.pdf
    label: $\mathrm{min}\Delta\phi(j_{0,1,2,3}, \mathcal{U})$
MinDPhiJ1234PuppiMETnoX:
    binning:
    - 0.0
    - 3.16
    - 0.05
    outpath: mindphij1234puppimetnox.pdf
    label: $\mathrm{min}\Delta\phi(j_{0,1,2,3}, \mathcal{U}_{\mathrm{puppi}})$
MTW:
    binning:
    - 0.0
    - 200.1
    - 4.0
    outpath: mtw.pdf
    label: $m_{\mathrm{T}}(\ell, p_{\mathrm{T}}^{\mathrm{miss}})$ (GeV)
MLL:
    binning:
    - 66.0
    - 116.1
    - 1.0
    outpath: mll.pdf
    label: $m_{\ell,\ell}$ (GeV)
nJetVeto:
    binning:
    - 0.0
    - 10.1
    - 1.0
    outpath: njetveto.pdf
    label: Jet veto multiplicity
nJetSelection:
    binning:
    - 0.0
    - 10.1
    - 1.0
    outpath: njetselection.pdf
    label: Jet selection multiplicity
LeadJetSelection_pt:
    binning:
    - 0.0
    - 1000.1
    - 50.0
    outpath: leadjetselection_pt.pdf
    label: Lead jet $p_{\mathrm{T}}$ (GeV)
LeadJetSelection_eta:
    binning:
    - -3.0
    - 3.01
    - 0.2
    outpath: leadjetselection_eta.pdf
    label: Lead jet $\eta$
LeadJetSelection_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: leadjetselection_phi.pdf
    label: Lead jet $\phi$
LeadJetSelection_chHEF:
    binning:
    - 0.0
    - 1.0
    - 0.04
    outpath: leadjetselection_chhef.pdf
    label: Lead jet charged hadron energy fraction
LeadJetSelection_neHEF:
    binning:
    - 0.0
    - 1.0
    - 0.04
    outpath: leadjetselection_nehef.pdf
    label: Lead jet neutral hadron energy fraction
LeadJetFwdSelection_pt:
    binning:
    - 0.0
    - 100.1
    - 2.0
    outpath: leadjetfwdselection_pt.pdf
    label: Lead forward jet $p_{\mathrm{T}}$ (GeV)
LeadJetFwdSelection_eta:
    binning:
    - -6.0
    - 6.01
    - 0.2
    outpath: leadjetfwdselection_eta.pdf
    label: Lead forward jet $\eta$
LeadJetFwdSelection_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: leadjetfwdselection_phi.pdf
    label: Lead forward jet $\phi$
NearestJetSelectionMET_pt:
    binning:
    - 0.0
    - 1000.1
    - 20.0
    outpath: nearestjetselectionmet_pt.pdf
    label: Jet nearest $\mathcal{U}$ $p_{\mathrm{T}}$ (GeV)
NearestJetSelectionMET_eta:
    binning:
    - -5.0
    - 5.01
    - 0.2
    outpath: nearestjetselectionmet_eta.pdf
    label: Jet nearest $\mathcal{U}$ $\eta$
NearestJetSelectionMET_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: nearestjetselectionmet_phi.pdf
    label: Jet nearest $\mathcal{U}$ $\phi$
SecondJetSelection_pt:
    binning:
    - 0.0
    - 1000.1
    - 20.0
    outpath: secondjetselection_pt.pdf
    label: Second jet $p_{\mathrm{T}}$ (GeV)
SecondJetSelection_eta:
    binning:
    - -5.0
    - 5.01
    - 0.2
    outpath: secondjetselection_eta.pdf
    label: Second jet $\eta$
SecondJetSelection_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: secondjetselection_phi.pdf
    label: Second jet $\phi$
nMuonVeto:
    binning:
    - 0.0
    - 10.1
    - 1.0
    outpath: nmuonveto.pdf
    label: Muon veto multiplicity
nMuonSelection:
    binning:
    - 0.0
    - 10.1
    - 1.0
    outpath: nmuonselection.pdf
    label: Muon selection multiplicity
LeadMuonSelection_pt:
    binning:
    - 0.0
    - 1000.1
    - 20.0
    outpath: leadmuonselection_pt.pdf
    label: Lead muon $p_{\mathrm{T}}$ (GeV)
LeadMuonSelection_eta:
    binning:
    - -3.0
    - 3.01
    - 0.2
    outpath: leadmuonselection_eta.pdf
    label: Lead muon $\eta$
LeadMuonSelection_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: leadmuonselection_phi.pdf
    label: Lead muon $\phi$
SecondMuonSelection_pt:
    binning:
    - 0.0
    - 1000.1
    - 20.0
    outpath: secondmuonselection_pt.pdf
    label: Second muon $p_{\mathrm{T}}$ (GeV)
SecondMuonSelection_eta:
    binning:
    - -5.0
    - 5.01
    - 0.2
    outpath: secondmuonselection_eta.pdf
    label: Second muon $\eta$
SecondMuonSelection_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: secondmuonselection_phi.pdf
    label: Second muon $\phi$
nElectronVeto:
    binning:
    - 0.0
    - 10.1
    - 1.0
    outpath: nelectronveto.pdf
    label: Electron veto multiplicity
nElectronSelection:
    binning:
    - 0.0
    - 10.1
    - 1.0
    outpath: nelectronselection.pdf
    label: Electron selection multiplicity
LeadElectronSelection_pt:
    binning:
    - 0.0
    - 1000.1
    - 20.0
    outpath: leadelectronselection_pt.pdf
    label: Lead electron $p_{\mathrm{T}}$ (GeV)
LeadElectronSelection_eta:
    binning:
    - -5.0
    - 5.01
    - 0.2
    outpath: leadelectronselection_eta.pdf
    label: Lead electron $\eta$
LeadElectronSelection_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: leadelectronselection_phi.pdf
    label: Lead electron $\phi$
SecondElectronSelection_pt:
    binning:
    - 0.0
    - 1000.1
    - 20.0
    outpath: secondelectronselection_pt.pdf
    label: Second electron $p_{\mathrm{T}}$ (GeV)
SecondElectronSelection_eta:
    binning:
    - -5.0
    - 5.01
    - 0.2
    outpath: secondelectronselection_eta.pdf
    label: Second electron $\eta$
SecondElectronSelection_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: secondelectronselection_phi.pdf
    label: Second electron $\phi$
nTauVeto:
    binning:
    - 0.0
    - 10.1
    - 1.0
    outpath: ntauveto.pdf
    label: Tau veto multiplicity
nTauSelection:
    binning:
    - 0.0
    - 10.1
    - 1.0
    outpath: ntauselection.pdf
    label: Tau selection multiplicity
LeadTauSelection_pt:
    binning:
    - 0.0
    - 1000.1
    - 20.0
    outpath: leadtauselection_pt.pdf
    label: Lead $\tau_{\mathrm{h}}$ $p_{\mathrm{T}}$ (GeV)
LeadTauSelection_eta:
    binning:
    - -5.0
    - 5.01
    - 0.2
    outpath: leadtauselection_eta.pdf
    label: Lead $\tau_{\mathrm{h}}$ $\eta$
LeadTauSelection_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: leadtauselection_phi.pdf
    label: Lead $\tau_{\mathrm{h}}$ $\phi$
LeadTauSelection_dphiMET:
    binning:
    - 0.0
    - 3.16
    - 0.05
    outpath: leadtauselection_dphiMET.pdf
    label: Lead $\tau_{\mathrm{h}}$ $\Delta\phi$ with $\mathrm{U}$
nIsoTrack:
    binning:
    - 0.0
    - 10.1
    - 1.0
    outpath: nisotrack.pdf
    label: Isolated track multiplicity
LeadIsoTrack_pt:
    binning:
    - 0.0
    - 500.1
    - 10.0
    outpath: leadisotrack_pt.pdf
    label: Lead isolated track $p_{\mathrm{T}}$ (GeV)
LeadIsoTrack_eta:
    binning:
    - -3.0
    - 3.01
    - 0.1
    outpath: leadisotrack_eta.pdf
    label: Lead isolated track $\eta$
LeadIsoTrack_phi:
    binning:
    - -3.20433
    - 3.20431
    - 0.12566
    outpath: leadisotrack_phi.pdf
    label: Lead isolated track $\phi$
nPhotonVeto:
    binning:
    - 0.0
    - 10.1
    - 1.0
    outpath: nphotonveto.pdf
    label: Photon veto multiplicity
nPhotonSelection:
    binning:
    - 0.0
    - 10.1
    - 1.0
    outpath: nphotonselection.pdf
    label: Photon selection multiplicity
nBJetVeto:
    binning:
    - 0.0
    - 10.1
    - 1.0
    outpath: nbjetveto.pdf
    label: $b$-tagged jet veto multiplicity
LeptonCharge:
    binning:
    - -4.0
    - 4.1
    - 1.0
    outpath: leptoncharge.pdf
    label: Total lepton charge
PV_npvsGood:
    binning:
    - 0.0
    - 100.0
    - 2.0
    outpath: pv_npvsgood.pdf
    label: Good PV multiplicity
Monojet:
    rename_samples:
        WJetsToTauHNu: WJetsToTauNu
        WJetsToTauLNu: WJetsToTauNu
        G1Jet: Minor
        SingleTop: Minor
        DYJetsToEE: Minor
        DYJetsToMuMu: Minor
        DYJetsToTauHTauH: Minor
        DYJetsToTauHTauL: Minor
        DYJetsToTauLTauL: Minor
DoubleMuon:
    rename_samples:
        TTJets: Minor
        SingleTop: Minor
        DYJetsToTauHTauL: Minor
        DYJetsToTauLTauL: Minor
        WJetsToMuNu: Minor
        WJetsToTauLNu: Minor
DoubleElectron:
    rename_samples:
        TTJets: Minor
        SingleTop: Minor
        DYJetsToTauHTauH: Minor
        DYJetsToTauHTauL: Minor
        DYJetsToTauLTauL: Minor
        WJetsToENu: Minor
        WJetsToTauLNu: Minor
        G1Jet: Minor
SingleTau:
    rename_samples:
        SingleTop: Minor
        DYJetsToEE: Minor
        DYJetsToMuMu: Minor
        DYJetsToTauHTauL: Minor
        DYJetsToTauLTauL: Minor
        WJetsToMuNu: Minor
        ZJetsToNuNu: Minor
        G1Jet: Minor
SingleMuon:
    rename_samples:
        SingleTop: Minor
        DYJetsToEE: Minor
        DYJetsToTauHTauH: Minor
        DYJetsToTauHTauL: Minor
        DYJetsToTauLTauL: Minor
        G1Jet: Minor
        ZJetsToNuNu: Minor
        WJetsToENu: Minor
        WJetsToTauHNu: Minor
SingleElectron:
    rename_samples:
        DYJetsToEE: Minor
        DYJetsToMuMu: Minor
        DYJetsToTauHTauH: Minor
        DYJetsToTauHTauL: Minor
        DYJetsToTauLTauL: Minor
        WJetsToMuNu: Minor
        WJetsToTauHNu: Minor
        G1Jet: Minor
        QCD: Minor
        ZJetsToNuNu: Minor
MonojetQCD:
    rename_samples:
        G1Jet: Minor
        VGamma: Minor
        Diboson: Minor
        VBS: Minor
        SingleTop: Minor
        DYJetsToEE: Minor
        DYJetsToMuMu: Minor
        DYJetsToTauHTauH: Minor
        DYJetsToTauHTauL: Minor
        DYJetsToTauLTauL: Minor
SingleMuonQCD:
    rename_samples:
        DYJetsToEE: Minor
        DYJetsToMuMu: Minor
        DYJetsToTauHTauH: Minor
        DYJetsToTauHTauL: Minor
        DYJetsToTauLTauL: Minor
        G1Jet: Minor
        WJetsToENu: Minor
        WJetsToTauHNu: Minor
        ZJetsToNuNu: Minor
SingleElectronQCD:
    rename_samples:
        G1Jet: Minor
        DYJetsToEE: Minor
        DYJetsToMuMu: Minor
        DYJetsToTauHTauH: Minor
        DYJetsToTauHTauL: Minor
        DYJetsToTauLTauL: Minor
        WJetsToMuNu: Minor
        WJetsToTauHNu: Minor
        ZJetsToNuNu: Minor
        QCD: Minor
defaults:
    rename_samples: {}
    legend_off_axes: true
    blind: false
    binvar: binvar0
    counts: sum_w
    variance: sum_ww
    sample: parent
    process_at_bottom: Minor
    process_colors:
        MET: black
        SingleMuon: black
        SingleElectron: black
        ZJetsToNuNu: '#80b1d3'
        WJetsToLNu: '#b3de69'
        WJetsToENu: '#b2df8a'
        WJetsToMuNu: '#b3de69'
        WJetsToTauNu: '#8dd3c7'
        WJetsToTauLNu: '#8dd3c7'
        WJetsToTauHNu: '#8dd3c7'
        Diboson: '#fdb462'
        DYJetsToLL: '#ffed6f'
        DYJetsToEE: '#fff6b3'
        DYJetsToMuMu: '#ffed6f'
        DYJetsToTauTau: '#ffe41a'
        DYJetsToTauLTauL: '#ffe41a'
        DYJetsToTauHTauL: '#ffe41a'
        DYJetsToTauHTauH: '#ffe41a'
        EWKV2Jets: '#bebada'
        SingleTop: '#fccde5'
        TTJets: '#bc80bd'
        QCD: '#fb8072'
        G1Jet: '#ccebc5'
        VGamma: '#ffffb3'
        Minor: '#d9d9d9'
    process_names:
        MET: MET
        SingleMuon: Single Muon
        SingleElectron: Single Electron
        ZJetsToNuNu: $\mathrm{Z}(\rightarrow \nu\nu)$+jets
        WJetsToLNu: $\mathrm{W}(\rightarrow l\nu)$+jets
        WJetsToENu: $\mathrm{W}(\rightarrow e\nu)$+jets
        WJetsToMuNu: $\mathrm{W}(\rightarrow \mu\nu)$+jets
        WJetsToTauNu: $\mathrm{W}(\rightarrow \tau\nu)$+jets
        WJetsToTauLNu: $\mathrm{W}(\rightarrow \tau_{l}\nu)$+jets
        WJetsToTauHNu: $\mathrm{W}(\rightarrow \tau_{h}\nu)$+jets
        Diboson: Diboson
        DYJetsToLL: $\mathrm{Z}/\gamma^{*}(\rightarrow ll)$+jets
        DYJetsToEE: $\mathrm{Z}/\gamma^{*}(\rightarrow ee)$+jets
        DYJetsToMuMu: $\mathrm{Z}/\gamma^{*}(\rightarrow \mu\mu)$+jets
        DYJetsToTauTau: $\mathrm{Z}/\gamma^{*}(\rightarrow \tau\tau)$+jets
        DYJetsToTauLTauL: $\mathrm{Z}/\gamma^{*}(\rightarrow \tau_{l}\tau_{l})$+jets
        DYJetsToTauHTauL: $\mathrm{Z}/\gamma^{*}(\rightarrow \tau_{l}\tau_{h})$+jets
        DYJetsToTauHTauH: $\mathrm{Z}/\gamma^{*}(\rightarrow \tau_{h}\tau_{h})$+jets
        EWKV2Jets: VBS
        SingleTop: Single Top
        TTJets: $t\bar{t}$+jets
        QCD: Multijet
        G1Jet: $\gamma$+jets
        VGamma: $V+\gamma$
        Minor: Minors
