query:
    groupby:
    - table
    - varname0
    - varname1
    - selection
    - parent
    - binvar0
    - binvar1
    tables:
        central: Events
    aliases: {}
    eval:
    -   ZCand_px: 'df: np.where(df.nMuonSelection==2, df.LeadMuonSelection_pt*np.cos(df.LeadMuonSelection_phi)+df.SecondMuonSelection_pt*np.cos(df.SecondMuonSelection_phi),
            np.zeros_like(df.nMuonSelection)) + np.where(df.nElectronSelection==2,
            df.LeadElectronSelection_pt*np.cos(df.LeadElectronSelection_phi)+df.SecondElectronSelection_pt*np.cos(df.SecondElectronSelection_phi),
            np.zeros_like(df.nMuonSelection))'
    -   ZCand_py: 'df: np.where(df.nMuonSelection==2, df.LeadMuonSelection_pt*np.sin(df.LeadMuonSelection_phi)+df.SecondMuonSelection_pt*np.sin(df.SecondMuonSelection_phi),
            np.zeros_like(df.nElectronSelection)) + np.where(df.nElectronSelection==2,
            df.LeadElectronSelection_pt*np.sin(df.LeadElectronSelection_phi)+df.SecondElectronSelection_pt*np.sin(df.SecondElectronSelection_phi),
            np.zeros_like(df.nElectronSelection))'
    -   ZCand_pt: 'df: np.sqrt(df.ZCand_px**2 + df.ZCand_py**2)'
    -   ZCand_phi: 'df: np.arctan2(df.ZCand_py, df.ZCand_px)'
    -   METnoX_ptParaZCandCent: 'df: df.METnoX_pt*np.cos(df.METnoX_phi-df.ZCand_phi)
            - df.ZCand_pt'
    -   METnoX_ptPerpZCandCent: 'df: df.METnoX_pt*np.sin(df.METnoX_phi-df.ZCand_phi)'
    -   ZCand_pt_bin: 'df: np.floor(df.ZCand_pt/5.)*5.'
    -   METnoX_ptParaZCandCent_bin: 'df: np.floor(df.METnoX_ptParaZCandCent/10.)*10.'
    -   METnoX_ptPerpZCandCent_bin: 'df: np.floor(df.METnoX_ptPerpZCandCent/10.)*10.'
    cutflows:
        DoubleMuon:
            selection_name: DoubleMuon
            selection: (IsCertified) & (Flag_goodVertices) & (Flag_globalSuperTightHalo2016Filter)
                & (Flag_HBHENoiseFilter) & (Flag_HBHENoiseIsoFilter) & (Flag_EcalDeadCellTriggerPrimitiveFilter)
                & (Flag_BadPFMuonFilter) & (Flag_eeBadScFilter) & (MET_dCaloMET<0.6)
                & (nJetSelection>0) & (nJetSelection==nJetVeto) & (LeadJetSelection_chHEF>0.1)
                & (LeadJetSelection_neHEF<0.8) & (LeadJetSelection_pt>200.) & (nPhotonVeto==0)
                & (nBJetVeto==0) & (MinDPhiJ1234METnoX>0.5) & (nMuonSelection==2)
                & (MLL>71.) & (MLL<111.) & (LeptonCharge==0.) & (nMuonVeto==2) & (nElectronVeto==0)
                & (nTauVeto==0)
            weight: '1.'
            hists:
            - ZCand_pt_METnoX_ptParaZCandCent
            - ZCand_pt_METnoX_ptPerpZCandCent
        DoubleElectron:
            selection_name: DoubleElectron
            selection: (IsCertified) & (Flag_goodVertices) & (Flag_globalSuperTightHalo2016Filter)
                & (Flag_HBHENoiseFilter) & (Flag_HBHENoiseIsoFilter) & (Flag_EcalDeadCellTriggerPrimitiveFilter)
                & (Flag_BadPFMuonFilter) & (Flag_eeBadScFilter) & (MET_dCaloMET<0.6)
                & (nJetSelection>0) & (nJetSelection==nJetVeto) & (LeadJetSelection_chHEF>0.1)
                & (LeadJetSelection_neHEF<0.8) & (LeadJetSelection_pt>200.) & (nPhotonVeto==0)
                & (nBJetVeto==0) & (MinDPhiJ1234METnoX>0.5) & (nElectronSelection==2)
                & (MLL>71.) & (MLL<111.) & (LeptonCharge==0.) & (nMuonVeto==0) & (nElectronVeto==2)
                & (nTauVeto==0)
            weight: '1.'
            hists:
            - ZCand_pt_METnoX_ptParaZCandCent
            - ZCand_pt_METnoX_ptPerpZCandCent
        DoubleMuonMu:
            selection_name: DoubleMuonMu
            selection: (IsCertified) & (Flag_goodVertices) & (Flag_globalSuperTightHalo2016Filter)
                & (Flag_HBHENoiseFilter) & (Flag_HBHENoiseIsoFilter) & (Flag_EcalDeadCellTriggerPrimitiveFilter)
                & (Flag_BadPFMuonFilter) & (Flag_eeBadScFilter) & (MET_dCaloMET<0.6)
                & (nJetSelection>0) & (nJetSelection==nJetVeto) & (LeadJetSelection_chHEF>0.1)
                & (LeadJetSelection_neHEF<0.8) & (LeadJetSelection_pt>200.) & (nPhotonVeto==0)
                & (nBJetVeto==0) & (MinDPhiJ1234METnoX>0.5) & (nMuonSelection==2)
                & (MLL>71.) & (MLL<111.) & (LeptonCharge==0.) & (nMuonVeto==2) & (nElectronVeto==0)
                & (nTauVeto==0)
            weight: '1.'
            hists:
            - ZCand_pt_METnoX_ptParaZCandCent
            - ZCand_pt_METnoX_ptPerpZCandCent
    hists:
        ZCand_pt_METnoX_ptParaZCandCent:
        -   table: 'df: ''{table_name}'''
        -   varname0: 'df: ''ZCand_pt'''
        -   varname1: 'df: ''METnoX_ptParaZCandCent'''
        -   selection: 'df: ''{selection_name}'''
        -   parent: 'df: df.parent'
        -   binvar0: 'df: df.ZCand_pt_bin'
        -   binvar1: 'df: df.METnoX_ptParaZCandCent_bin'
        -   count: 'df: 1.'
        -   sum_w: 'df: {weight}'
        -   sum_ww: 'df: df.sum_w**2'
        -   sum_wZCand_pt: 'df: df.sum_w*df.ZCand_pt'
        ZCand_pt_METnoX_ptPerpZCandCent:
        -   table: 'df: ''{table_name}'''
        -   varname0: 'df: ''ZCand_pt'''
        -   varname1: 'df: ''METnoX_ptPerpZCandCent'''
        -   selection: 'df: ''{selection_name}'''
        -   parent: 'df: df.parent'
        -   binvar0: 'df: df.ZCand_pt_bin'
        -   binvar1: 'df: df.METnoX_ptPerpZCandCent_bin'
        -   count: 'df: 1.'
        -   sum_w: 'df: {weight}'
        -   sum_ww: 'df: df.sum_w**2'
        -   sum_wZCand_pt: 'df: df.sum_w*df.ZCand_pt'
files: []
